### ISSUE TITLE
Environments isuues

### ISSUE THREAD

**Issue by C-Ll-l** [nachifur/automatic_label_correction_based_CCEDD#5]
Hello, the existing code running environment is implemented on Ubuntu If I want to run under windows, please do U have detailed requirements.txt, or detailed Windows environment setup configuration instructions?

**Comment by nachifur** [comment]
Thank you very much for your interest in our project.

1. I recommend running LLPC on ubuntu, which is the choice for most deep learning projects.
2. LLPC can theoretically be run on windows, as the code is written entirely in python. You may need to change some file paths by debugging the code.
3. You can use the following command to install the runtime environment.
```
conda env create -f install.yaml
```
https://github.com/nachifur/LLPC/blob/main/install.yaml

**Comment by nachifur** [comment]
This issue occurred due to a bug in the configuration file and has been fixed (`BCELOSS`->`BCELoss`).
![image](https://user-images.githubusercontent.com/23144348/177462817-eaaf79b1-6971-4fcb-a5be-3d5a49f42305.png)
