### ISSUE TITLE
How to use CCEDD for image segmentation task

### ISSUE THREAD

**Issue by hinatanvir** [nachifur/automatic_label_correction_based_CCEDD#6]
hi, I know the work that you provide is not for the purpose of semantic segmentation. However, I want to confirm that is there a way it can be used to produce ground truths masks for segmented nuclei and used those for training the segmentation model. Any hint regarding information or label from json files that may be used for the purpose would be helpful, becuase i see those images in the research study. Please help.

**Comment by nachifur** [comment]
See labelme about semantic segmentation.

https://github.com/wkentaro/labelme
